// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portal.Infrastructure.Contexts;

namespace Portal.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191208152500_trenings")]
    partial class trenings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Portal.Application.Models.Carnet", b =>
                {
                    b.Property<Guid>("CarnetID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientID");

                    b.Property<DateTime>("DateEnd");

                    b.Property<DateTime>("DateStart");

                    b.Property<bool>("IsActive");

                    b.Property<Guid?>("TypeCarnetTypeID");

                    b.HasKey("CarnetID");

                    b.HasIndex("ClientID");

                    b.HasIndex("TypeCarnetTypeID");

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("Portal.Application.Models.CarnetType", b =>
                {
                    b.Property<Guid>("CarnetTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("CarnetTypeID");

                    b.ToTable("CarnetTypes");
                });

            modelBuilder.Entity("Portal.Application.Models.Entrance", b =>
                {
                    b.Property<Guid>("EntranceID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CarnetID");

                    b.Property<DateTime>("Date");

                    b.HasKey("EntranceID");

                    b.ToTable("Entrances");
                });

            modelBuilder.Entity("Portal.Application.Models.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ContactData");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<bool>("ProfileComplete");

                    b.Property<string>("Role");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("PersonID");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("Portal.Application.Models.PersonTraining", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClientPersonID");

                    b.Property<Guid>("TrainigID");

                    b.Property<Guid?>("TrainingID");

                    b.HasKey("PersonID");

                    b.HasIndex("ClientPersonID");

                    b.HasIndex("TrainingID");

                    b.ToTable("PersonTrainings");
                });

            modelBuilder.Entity("Portal.Application.Models.Training", b =>
                {
                    b.Property<Guid>("TrainingID")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Title");

                    b.Property<Guid?>("TrainerPersonID");

                    b.Property<int>("Type");

                    b.HasKey("TrainingID");

                    b.HasIndex("TrainerPersonID");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Portal.Application.Models.Client", b =>
                {
                    b.HasBaseType("Portal.Application.Models.Person");

                    b.Property<int>("Sex");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Portal.Application.Models.Trainer", b =>
                {
                    b.HasBaseType("Portal.Application.Models.Person");


                    b.ToTable("Trainer");

                    b.HasDiscriminator().HasValue("Trainer");
                });

            modelBuilder.Entity("Portal.Application.Models.Carnet", b =>
                {
                    b.HasOne("Portal.Application.Models.Client")
                        .WithMany("Carnets")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Portal.Application.Models.CarnetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeCarnetTypeID");
                });

            modelBuilder.Entity("Portal.Application.Models.PersonTraining", b =>
                {
                    b.HasOne("Portal.Application.Models.Client", "Client")
                        .WithMany("PersonTraining")
                        .HasForeignKey("ClientPersonID");

                    b.HasOne("Portal.Application.Models.Training", "Training")
                        .WithMany("PersonTraining")
                        .HasForeignKey("TrainingID");
                });

            modelBuilder.Entity("Portal.Application.Models.Training", b =>
                {
                    b.HasOne("Portal.Application.Models.Trainer", "Trainer")
                        .WithMany("Training")
                        .HasForeignKey("TrainerPersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
